name: 'Terraform Steps Win'
description: 'Reusable Steps for Terraform Lifecycle'

inputs:
  target_environment:
    description: 'The target environment (non-prod, prod)'
    required: true
  terraform_apply:
    description: 'Flag to apply Terraform changes (default: no)'
    required: false
  work_directory:
    description: 'working directory'
    required: true

runs:
    using: "composite"
    steps:
    - name: "Terraform Format"
      id: fmt
      run: |
        echo This is terraform-action repo
        echo The current directory is %cd%
        terraform fmt -recursive
      working-directory: terraform
      shell: cmd

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform
      shell: cmd 

    - name: "Terraform Validate"
      id: validate
      run: terraform validate -no-color
      working-directory: terraform
      shell: cmd  # Run in Command Prompt

    - name: Terraform Plan
      id: plan
      run: |       
        echo The current directory is %cd%
        echo current env is ${{matrix.envn}}
        terraform plan -var-file=${{matrix.envn}}.tfvars -out=${{matrix.envn}}-tfplan
      working-directory: terraform
      shell: cmd 
