name: 'Terraform Steps'
description: 'Reusable Steps for Terraform Lifecycle'

inputs:
  target_environment:
    description: 'The target environment (non-prod, prod)'
    required: true
  terraform_apply:
    description: 'Flag to apply Terraform changes (default: no)'
    required: false

  work_directory:
    description: 'working directory'
    required: true

   
        
runs:
    using: "composite"
    steps:
     - name: "Terraform Format"
       id: fmt
       run: |
         echo "This is terraform-action repo"
         echo "work_directory is ${{inputs.work_directory}}"
         echo "The current directory is $(pwd)"
         terraform fmt -recursive
       working-directory: terraform
       shell: bash     

     - name: Terraform Init
       id: init
       run: |
         cat <<-TF_BACKEND > backend.tf
         terraform {
          backend "azurerm" {
            resource_group_name = "rg-my"
            storage_account_name = "teststoragemy"
            container_name       = "terraform-state"
            key                  = "terraform.tfstate"
           }
          }
         TF_BACKEND  
         
         terraform init     
       working-directory: terraform      
       shell: bash
        

     - name: "Terraform Validate"
       id: validate
       run: terraform validate -no-color
       working-directory: terraform
       shell: bash
        
     - name: Terraform Plan
       id: plan
       run: |
         echo 'environment: ${{ inputs.target_environment }}'
         echo 'environment: ${{ inputs.terraform_apply }}'
         #echo 'Merged to Branch:${{ github.event.pull_request.base.ref }}'
         terraform plan -var-file=${{ inputs.target_environment}}.tfvars -out=${{ inputs.target_environment}}-tfplan
       working-directory: terraform 
       shell: bash

     - name: "Terraform Apply"
       if: ${{ inputs.terraform_apply != '' && inputs.terraform_apply == 'true'}}
       run: terraform apply ${{ inputs.target_environment}}-tfplan
       working-directory: terraform
       shell: bash 

