name: 'Terraform Steps'
description: 'Run Terraform from PRs. If terraform apply is yes, then apply terraform changes'


inputs:
    target_environment:
        required: true
        
   
        
runs:
    using: "composite"
    steps:
     - name: "Terraform Format"
       id: fmt
       run: |
         echo "The current directory is $(pwd)"
         terraform fmt -recursive
       working-directory: terraform
       shell: bash     

     - name: Terraform Init
       id: init
       run: terraform init
         # terraform init \
         #   -backend-config="storage_account_name=yourstorageaccount" \
         #   -backend-config="container_name=terraform-state" \
         #  -backend-config="key=${{ env.STATE_FILE }}" \
         #   -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
       working-directory: terraform      
       shell: bash
        

     - name: "Terraform Validate"
       id: validate
       run: terraform validate -no-color
       working-directory: terraform
       shell: bash
        
     - name: Terraform Plan
       id: plan
       run: |
         echo '${{ inputs.target_environment }}'
         echo 'Merged to Branch:${{ github.event.pull_request.base.ref }}'
         terraform plan -var-file=${{ inputs.target_environment}}.tfvars -out=${{ inputs.target_environment}}-tfplan
       working-directory: terraform 
       shell: bash

     - name: "Terraform Apply"
       if: ${{ inputs.terraform_apply != '' && inputs.terraform_apply == 'yes'}}
       run: terraform apply ${{ inputs.target_environment}}-tfplan
       working-directory: terraform
       shell: bash 